name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - uses: actions/checkout@v3
    - name: Build and pushing new docker image to docker hub
      run: ./build_and_push.sh

    - uses: actions/checkout@v3
    - name: Send notification to telegram chat
      run: pip3 install -r ./utils/requirements.txt; python3 ./utils/telegram_notification.py -t $TELEGRAM_BOT_TOKEN -c $TELEGRAM_CHAT_ID_FOR_NOTIFICATIONS -m "$(cat ./freads/README.md)"
